<?php

namespace Tribuca\Bundle\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsPaperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsPaperRepository extends EntityRepository
{
}
